[package]
name = "kvs"
version = "0.1.0"
authors = ["Jan-Christoph Klie <git@mrklie.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
